### PR TITLE
Create an Interactive Readme

### PR DESCRIPTION
**Pull request by MinerBigWhale**
Relate to issue #13

Added Readme with full page Screenshot of the portfolio, Badges and 101 of Readme (install, usage,
contributea and license)

Images are in public folder and wil show on readme when merge to master 😉

here are the screenshots :
home

### CODE REVIEW

**Comment by stephin007** [comment]
@MinerBigWhale please remove the screenshots of the aboutMe and the projects, I don't need that as of now, the first screenshot will be enough! :)
please do the necessary changes and raise another PR from another branch!

**Comment by stephin007** [comment]
@MinerBigWhale Also please add me as a reviewer as soon as you raise another PR

**Comment by MinerBigWhale** [comment]
Hi @stephin007 , can i just push a new commit without the screenshot ? 
I don't know how to make you reviewer

**Comment by stephin007** [comment]
Sure @MinerBigWhale only keep the front page screenshot rest  please remove it!

**Comment by MinerBigWhale** [comment]
Done 🎉 
@stephin007 could you review it please ?

**Pull request merged**
