### PR TITLE
#7 Make all the data in the portfolio dynamic. 

### PR DESCRIPTION
**Pull request by ZenVega**
Same pull request but a different branch

### CODE REVIEW

**Comment by ZenVega** [comment]
Okay, that should be it. could you also add the hacktoberfest label on that PR? that would be great! thanks

**Comment by stephin007** [comment]
hey @ZenVega sorry for replying late.
But I found a problem in this PR, you haven't changed the links of the projects, every project is opening to a single website
i.e. you did not make the projects website link dynamic :(

Can you please change that and raise a PR again. Then only I can merge it.
rest Everything is perfect ⭐

**Comment by stephin007** [comment]
@ZenVega no need to change anything, ill manage! THankyou so much for the contribution! ❤️

**Comment by ZenVega** [comment]
ok cool.

**Pull request merged**
